<?php

namespace Test\Datamolino;

use Datamolino\Agenda;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-02-15 at 17:03:07.
 */
class AgendaTest extends ApiClientTest
{
    /**
     * @var Agenda
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Agenda;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Datamolino\Agenda::getListing
     */
    public function testGetListing()
    {
        $this->object->getListing();
    }

    /**
     * @covers Datamolino\Agenda::createNew
     */
    public function testCreateNew()
    {
        $this->object->createNew([
            "name" => "DataMolino s. r. o.",
            "address" => [
                "street" => "Zochova",
                "building_no" => "6 - 8",
                "city" => "Bratislava",
                "postal_code" => "811 03",
                "country" => "sk"
            ],
            "company_id" => "47327961",
            "company_tax_id" => "2023832976",
            "company_vat_id" => null,
            "home_currency" => "EUR",
            "email_alias" => "datamolino123",
            "email_whitelist" => "test@yahoo.com, invoices@gmail.com"
            ]
        );
    }
}
