<?php

namespace Test\Datamolino;
use Datamolino\User;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-02-15 at 17:03:07.
 */
class UserTest extends ApiClientTest
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
